apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-frontend
  labels:
    app: fintech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintech-frontend
  template:
    metadata:
      labels:
        app: fintech-frontend
    spec:
      containers:
      - name: fintech-frontend
        image: ragnargp/fintech-frontend
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://ac937de20a7c340b7b97d75406fb1fb3-1675112639.us-east-1.elb.amazonaws.com:3000/api"
        - 
---
kind: Service
apiVersion: v1
metadata:
  name: fintech-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: fintech-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
